name: CI

on:
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install --frozen-lockfile

      - name: run lint
        run: yarn run lint

      - name: check format
        run: yarn run format:check

      - name: build test
        run: yarn run build

      - name: code test
        run: yarn run test
